# Generated by Django 3.2.25 on 2025-01-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0003_maincategory_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to='tuerny_app.subcategory'),
        ),
    ]
