# Generated by Django 3.2.25 on 2025-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media_extra',
            field=models.FileField(blank=True, help_text='Medya dosyası (resim, video veya ses dosyası) yükleyebilirsiniz.', null=True, upload_to='blog_media/'),
        ),
    ]
