# Generated by Django 5.1.5 on 2025-01-21 12:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0011_blog_short_description_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
