# Generated by Django 5.1.5 on 2025-01-22 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0012_maincategory_slug_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='voted_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
