# Generated by Django 5.1.5 on 2025-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0013_polloption_voted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
