# Generated by Django 5.1.5 on 2025-01-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0015_remove_blog_writer_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_blog', to='tuerny_app.blog')),
            ],
        ),
    ]
