# Generated by Django 5.1.5 on 2025-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0023_savedblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
