# Generated by Django 5.1.5 on 2025-02-22 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0024_question_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_newsletter', models.BooleanField(default=False)),
                ('email_question_votes', models.BooleanField(default=True)),
                ('email_question_answers', models.BooleanField(default=True)),
                ('email_comment_replies', models.BooleanField(default=True)),
                ('email_security_alerts', models.BooleanField(default=True)),
                ('email_comment_reactions', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('notify_campaigns', models.BooleanField(default=True)),
                ('notify_trending', models.BooleanField(default=False)),
                ('notify_question_votes', models.BooleanField(default=True)),
                ('notify_question_answers', models.BooleanField(default=True)),
                ('notify_comment_replies', models.BooleanField(default=True)),
                ('notify_comment_reactions', models.BooleanField(default=True)),
                ('notify_security_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
