# Generated by Django 5.1.5 on 2025-02-25 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0025_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='saved_users',
            field=models.ManyToManyField(blank=True, related_name='saved_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
