# Generated by Django 5.1.5 on 2025-03-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0028_customuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('header', 'Başlık'), ('subheader', 'Alt Başlık'), ('paragraph', 'Paragraf'), ('image', 'Resim'), ('video', 'Video'), ('product', 'Ürün')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tuerny_app.blog')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuerny_app.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
