# Generated by Django 5.1.5 on 2025-03-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0029_blogcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
