# Generated by Django 5.1.5 on 2025-03-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0031_remove_product_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extra_product',
            field=models.ManyToManyField(blank=True, related_name='extra_product_blog', to='tuerny_app.product'),
        ),
        migrations.AddField(
            model_name='blog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_blog', to='tuerny_app.product'),
        ),
    ]
