# Generated by Django 5.1.5 on 2025-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0032_blog_extra_product_blog_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
