# Generated by Django 5.0.1 on 2025-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0037_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='email_comment_reactions',
            new_name='email_poll_votes',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='email_comment_replies',
            new_name='email_question_approval',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_question_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_poll_votes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_question_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_question_comments',
            field=models.BooleanField(default=True),
        ),
    ]
