# Generated by Django 5.0.1 on 2025-03-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuerny_app', '0038_rename_email_comment_reactions_usersettings_email_poll_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email_question_answers',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_comment_reactions',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_comment_replies',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='notify_question_answers',
        ),
    ]
